config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts, only: [:show, :index]
  resources :tags, only: [:show]

  root 'posts#index'

  namespace :admin do
    resources :posts, except: [:show, :index]
    resources :pictures, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :summary, :body, presence: true

  mount_uploader :image, ImageUploader

  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings, :dependent => :destroy

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"
  
  protected

  def check_admin
    redirect_to root_path, alert: "У вас нет прав доступа к данной странице" unless current_user.admin?
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < ApplicationController
  
  def create
    @picture = Picture.new(picture_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => {
        url: @picture.image.url(:large),
        picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok }}
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [ :edit, :update, :destroy ]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Пост успешно создан'
    else
      flash.now[:danger] = "Статья не создана"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Пост успешно обновлен'
    else
      flash.now[:danger] = "Статья не обновлена"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Пост успешно удален'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :all_tags, :summary, :body, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, except: [:create, :destroy]

  def create
    @picture = Picture.new(picture_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => {
        url: @picture.image.url(:large),
        picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok }}
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def class_for(name)
    {
      success: "alert-success",
      error: "alert-danger",
      danger: "alert-success",
      alert: "alert-warning",
      notice: "alert-info",
    }[name.to_sym] || name
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
  <div>
    <p><%= t('common.errors') %><p>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @post], html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor'  %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn button-add' %>
    <%= link_to t('common.back'), :back, class: 'btn button-back' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h2><%= t('.title')%></h2>

<%= render 'form' %>

app/views/admin/posts/new.html.erb
<h2><%= t('posts.new.title') %></h2>

<%= render 'form' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Руби, рельсы, рок-н-ролл!!!</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content-wrapper">
    <div class="navigation">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="/"><span>Главная</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><span>Обо мне</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><span>Услуги</span></a>
          </li>

          <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <span><%= link_to 'Новая статья', new_admin_post_path, class: 'nav-link' %></span>
          </li>
          <% elsif user_signed_in?%>
          <li class="nav-item">
            <span><%= link_to 'Выход', destroy_user_session_path, method: :delete, class: 'nav-link' %></span>
          </li>
          <% else %>
          <li class="nav-item">
            <span><%= link_to 'Вход', new_user_session_path, class: 'nav-link' %></span>
          </li>
          <li class="nav-item">
            <span><%= link_to 'Регистрация', new_user_registration_path, class: 'nav-link' %></span>
          </li>
          <% end %>

        </ul>

    </div>
    <div class="header">
        <h1><a href="/">Руби, рельсы, рок-н-ролл!!!</a></h1>
        <span>Пилю веб-приложения на RoR и пишу об этом)</span>
    </div>
    <div class="blog">
      <div class="row">
        <% flash.each do |name, message|%>
          <div class="alert <%= class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
        <% end %>
      </div>
      <%= yield %>

    </div>
    <div class="about">
          <h3>Об авторе</h3>
            <!-- <img src="images/ava.jpg"> -->
          <p>
              Привет! Меня зовут Александр Левашов. В 30 лет я
              решил изменить свою жизнь, освоив новую профессию
              веб-разработчика. На страницах этого блога я рассказываю
              о том, как иду по этому сложному, но интересному пути.
          </p>
    </div>
    <div class="footer">
          <p>Alevashov.ru, 2017</p>
    </div>
  </div>
  <script id="dsq-count-scr" src="//alevashov.disqus.com/count.js" async></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Руби, рельсы, рок-н-ролл!!!</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content-wrapper">
    <div class="navigation">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="/"><span>Главная</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><span>Обо мне</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><span>Услуги</span></a>
          </li>
          
          <% if user_signed_in? %>
          <li class="nav-item">
            <span><%= link_to 'Новая статья', new_post_path, class: 'nav-link' %></span>
          </li>
          <li class="nav-item">
            <span><%= link_to 'Выход', destroy_user_session_path, method: :delete, class: 'nav-link' %></span>
          </li>
          <% else %>
          <li class="nav-item">
            <span><%= link_to 'Вход', new_user_session_path, class: 'nav-link' %></span>
          </li>
          <li class="nav-item">
            <span><%= link_to 'Регистрация', new_user_registration_path, class: 'nav-link' %></span>
          </li>
          <% end %>

        </ul>

    </div>
    <div class="header">
        <h1><a href="/">Руби, рельсы, рок-н-ролл!!!</a></h1>
        <span>Пилю веб-приложения на RoR и пишу об этом)</span>
    </div>
    <div class="blog">
      <div class="row">
        <% flash.each do |name, message|%>
          <div class="alert <%= class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
        <% end %>
      </div>
      <%= yield %>

    </div>
    <div class="about">
          <h3>Об авторе</h3>
            <!-- <img src="images/ava.jpg"> -->
          <p>
              Привет! Меня зовут Александр Левашов. В 30 лет я
              решил изменить свою жизнь, освоив новую профессию
              веб-разработчика. На страницах этого блога я рассказываю
              о том, как иду по этому сложному, но интересному пути.
          </p>
    </div>
    <div class="footer">
          <p>Alevashov.ru, 2017</p>
    </div>
  </div>
  <script id="dsq-count-scr" src="//alevashov.disqus.com/count.js" async></script>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*

request.base.url + original_fullpath

var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
  var disqus_config = function () {
    this.page.url = 'http://alevashov.ru<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://alevashov.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div>
    <p><%= t('common.errors') %><p>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor'  %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn button-add' %>
    <%= link_to t('common.back'), :back, class: 'btn button-back' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="article">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <span><%= post.created_at.to_date.strftime("%d %B, %Y") %></span>
    <% if user_signed_in?  && current_user.admin? %>
      |
      <%= link_to 'Изменить', edit_admin_post_path(post) %>
      |
      <%= link_to 'Удалить', admin_post_path(post), method: :delete, data: { confirm: 'Вы уверены?' } %>
    <% end %>
    <p>
      <%= image_tag post.image.url(:large), class: 'img-show' if post.image? %>
      <%= post.summary %>
    </p>
    <div class="read-more">
      <%= link_to 'Читать дальше', post_path(post) %>
    </div>
    <div class="tags">
      <%= raw post.tags.map(&:name).map {|t| link_to t, tag_path(t), class: 'tag'}.join(' ') %>
    </div>
</div>

app/views/posts/index.html.erb
<%= render @posts %>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/show.html.erb
<div class="article">
    <h2><%= @post.title %></h2>
    <span><%= @post.created_at.to_date.strftime("%d %B, %Y ") %></span>
    <% if user_signed_in? && current_user.admin?%>
      |
      <%= link_to 'Изменить', edit_admin_post_path(@post) %>
      |
      l<%= link_to 'Удалить', admin_post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
    <% end %>
    <p>
      <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
      <%= @post.body.html_safe %>
    </p>
</div>
<div class="comments">
  <%= render 'disqus' %>
</div>

app/views/tags/show.html.erb
<h2><%= @tag.name %></h2>

<% if @tag.posts.empty?  %>
  <p>Статей нет</p>
<% else %>
  <%= render @tag.posts %>
<% end %>